# Generated by Django 2.0.3 on 2018-03-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='artist',
        ),
        migrations.AddField(
            model_name='lyrics',
            name='written_by',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
