# Generated by Django 2.0.3 on 2018-03-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0002_auto_20180329_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='written_by',
            field=models.CharField(max_length=100),
        ),
    ]
