# Generated by Django 2.0.3 on 2018-03-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0003_auto_20180329_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applyrics.Lyrics')),
            ],
        ),
    ]
