# Generated by Django 2.0.3 on 2018-03-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0004_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='lyrics',
        ),
    ]
