# Generated by Django 2.0.3 on 2018-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0006_auto_20180329_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='text',
            field=models.BinaryField(),
        ),
    ]
