# Generated by Django 2.0.3 on 2018-03-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0008_auto_20180330_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='text',
            field=models.BinaryField(),
        ),
    ]
