# Generated by Django 2.0.3 on 2018-03-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0009_auto_20180330_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='text',
            field=models.TextField(),
        ),
    ]
