# Generated by Django 2.0.3 on 2018-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0010_auto_20180330_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=70)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
