# Generated by Django 2.0.3 on 2018-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0011_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='song_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
