# Generated by Django 2.0.3 on 2018-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0013_correction_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=70)),
            ],
        ),
    ]
