# Generated by Django 2.0.3 on 2018-04-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0014_frontword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
