# Generated by Django 2.0.3 on 2018-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0015_submittedlyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedlyrics',
            name='writer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
