# Generated by Django 2.0.3 on 2018-04-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0017_auto_20180401_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedlyrics',
            name='finalized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
