# Generated by Django 2.0.3 on 2018-04-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0018_submittedlyrics_finalized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedlyrics',
            old_name='finalized',
            new_name='replaced_new_lines',
        ),
    ]
