# Generated by Django 2.0.3 on 2018-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0019_auto_20180401_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedlyrics',
            name='published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
