# Generated by Django 2.0.3 on 2018-04-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0020_submittedlyrics_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='replaced_new_lines',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
