# Generated by Django 2.0.3 on 2018-04-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0023_auto_20180408_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedlyrics',
            name='replaced_new_lines',
            field=models.BooleanField(default=False),
        ),
    ]
