# Generated by Django 2.0.3 on 2018-04-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0025_auto_20180409_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontWord',
        ),
    ]
