# Generated by Django 2.0.3 on 2018-04-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyrics', '0026_delete_frontword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='written_by',
            field=models.CharField(max_length=500),
        ),
    ]
